name: HaxRDP

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: DOWNLOADING
      run: Invoke-webrequest https://bin.equinox.io/c/iVmDzA7iaHb/ngrok-stable-windows-amd64.zip -Outfile ngrok.zip
    - name: EXTRACT
      run: Expand-Archive ngrok.zip
    - name: AUTENTIFIKASI
      run: .\ngrok\ngrok.exe authtoken 21HY9RH2FeEdvQwqp72dOmNdiFM_341HfpJHNerxDWotUib9r
    - name: ENABLE TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal 
Server'-name "rDenyTSConnections" -value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal
Server\WinStations\RDP-tcp' -Name "runneradmin" -Password (ConvertTo-SecureString -
AsPlainText "P@ssw0rd!" -Force)
    - name: DONE!
      run: .\ngrok\ngrok.exe tcp 3389
